--- #YAML:1.0
name:               Danga-Socket-AnyEvent
version:            0.04
abstract:           Reimplementation of Danga::Socket in terms of AnyEvent
author:
    - Martin Atkins <mart@degeneration.co.uk>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:      1
    Carp:          0
    fields:        0
    POSIX:         0
    Sys::Syscall:  0
    Test::More:    0
    Time::HiRes:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
